@echo off
bio_alg performance random 20 0 data/qap/ tai60a results\MSLS_tests\20_msls_performance_results.txt greedyLS
bio_alg performance random 20 0 data/qap/ tai60a results\MSLS_tests\20_msls_performance_results.txt steepestLS
bio_alg performance random 20 0 data/qap/ tai60a results\MSLS_tests\20_msls_performance_results.txt iterativeImprovement
bio_alg performance random 50 0 data/qap/ tai60a results\MSLS_tests\50_msls_performance_results.txt greedyLS
bio_alg performance random 50 0 data/qap/ tai60a results\MSLS_tests\50_msls_performance_results.txt steepestLS
bio_alg performance random 50 0 data/qap/ tai60a results\MSLS_tests\50_msls_performance_results.txt iterativeImprovement
bio_alg performance random 100 0 data/qap/ tai60a results\MSLS_tests\100_msls_performance_results.txt greedyLS
bio_alg performance random 100 0 data/qap/ tai60a results\MSLS_tests\100_msls_performance_results.txt steepestLS
bio_alg performance random 100 0 data/qap/ tai60a results\MSLS_tests\100_msls_performance_results.txt iterativeImprovement
bio_alg performance random 150 0 data/qap/ tai60a results\MSLS_tests\150_msls_performance_results.txt greedyLS
bio_alg performance random 150 0 data/qap/ tai60a results\MSLS_tests\150_msls_performance_results.txt steepestLS
bio_alg performance random 150 0 data/qap/ tai60a results\MSLS_tests\150_msls_performance_results.txt iterativeImprovement
bio_alg performance random 200 0 data/qap/ tai60a results\MSLS_tests\200_msls_performance_results.txt greedyLS
bio_alg performance random 200 0 data/qap/ tai60a results\MSLS_tests\200_msls_performance_results.txt steepestLS
bio_alg performance random 200 0 data/qap/ tai60a results\MSLS_tests\200_msls_performance_results.txt iterativeImprovement
bio_alg performance random 300 0 data/qap/ tai60a results\MSLS_tests\300_msls_performance_results.txt greedyLS
bio_alg performance random 300 0 data/qap/ tai60a results\MSLS_tests\300_msls_performance_results.txt steepestLS
bio_alg performance random 300 0 data/qap/ tai60a results\MSLS_tests\300_msls_performance_results.txt iterativeImprovement
bio_alg performance random 500 0 data/qap/ tai60a results\MSLS_tests\500_msls_performance_results.txt greedyLS
bio_alg performance random 500 0 data/qap/ tai60a results\MSLS_tests\500_msls_performance_results.txt steepestLS
bio_alg performance random 500 0 data/qap/ tai60a results\MSLS_tests\500_msls_performance_results.txt iterativeImprovement
bio_alg performance random 20 0 data/qap/ chr22a results\MSLS_tests\20_msls_performance_results.txt greedyLS
bio_alg performance random 20 0 data/qap/ chr22a results\MSLS_tests\20_msls_performance_results.txt steepestLS
bio_alg performance random 20 0 data/qap/ chr22a results\MSLS_tests\20_msls_performance_results.txt iterativeImprovement
bio_alg performance random 50 0 data/qap/ chr22a results\MSLS_tests\50_msls_performance_results.txt greedyLS
bio_alg performance random 50 0 data/qap/ chr22a results\MSLS_tests\50_msls_performance_results.txt steepestLS
bio_alg performance random 50 0 data/qap/ chr22a results\MSLS_tests\50_msls_performance_results.txt iterativeImprovement
bio_alg performance random 100 0 data/qap/ chr22a results\MSLS_tests\100_msls_performance_results.txt greedyLS
bio_alg performance random 100 0 data/qap/ chr22a results\MSLS_tests\100_msls_performance_results.txt steepestLS
bio_alg performance random 100 0 data/qap/ chr22a results\MSLS_tests\100_msls_performance_results.txt iterativeImprovement
bio_alg performance random 150 0 data/qap/ chr22a results\MSLS_tests\150_msls_performance_results.txt greedyLS
bio_alg performance random 150 0 data/qap/ chr22a results\MSLS_tests\150_msls_performance_results.txt steepestLS
bio_alg performance random 150 0 data/qap/ chr22a results\MSLS_tests\150_msls_performance_results.txt iterativeImprovement
bio_alg performance random 200 0 data/qap/ chr22a results\MSLS_tests\200_msls_performance_results.txt greedyLS
bio_alg performance random 200 0 data/qap/ chr22a results\MSLS_tests\200_msls_performance_results.txt steepestLS
bio_alg performance random 200 0 data/qap/ chr22a results\MSLS_tests\200_msls_performance_results.txt iterativeImprovement
bio_alg performance random 300 0 data/qap/ chr22a results\MSLS_tests\300_msls_performance_results.txt greedyLS
bio_alg performance random 300 0 data/qap/ chr22a results\MSLS_tests\300_msls_performance_results.txt steepestLS
bio_alg performance random 300 0 data/qap/ chr22a results\MSLS_tests\300_msls_performance_results.txt iterativeImprovement
bio_alg performance random 500 0 data/qap/ chr22a results\MSLS_tests\500_msls_performance_results.txt greedyLS
bio_alg performance random 500 0 data/qap/ chr22a results\MSLS_tests\500_msls_performance_results.txt steepestLS
bio_alg performance random 500 0 data/qap/ chr22a results\MSLS_tests\500_msls_performance_results.txt iterativeImprovement
